tanbamaapp/api/urls.py
from django.conf.urls import url, include
from .views import UserRegistrationAPIView, WeightListCreateAPIView, WeightDetailAPIView, DrugListCreateAPIView, RxListCreateAPIView, RxDetailAPIView, DrugDetailAPIView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

api_user = [
    url(r'^$', UserRegistrationAPIView.as_view(), name="list"),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    
]

api_body = [
    url(r'^weight/$', WeightListCreateAPIView.as_view(), name="list"),
    url(r'^weight/(?P<pk>[0-9]+)/$', WeightDetailAPIView.as_view(), name="detail"),
    url(r'^drug/$', DrugListCreateAPIView.as_view(), name="list"),
    url(r'^drug/(?P<pk>[0-9]+)/$', DrugDetailAPIView.as_view(), name="detail"),
    url(r'^rx/$', RxListCreateAPIView.as_view(), name="list"),
    url(r'^rx/(?P<pk>[0-9]+)/$', RxDetailAPIView.as_view(), name="detail"),
    
]

    


urlpatterns = [
    url(r'^body/', include(api_body)),
    url(r'^user/', include(api_user)),
]

tanbamaapp/pinax/messages/urls.py
from django.conf.urls import url

from . import views

app_name = "pinax_messages"

urlpatterns = [
    url(r"^inbox/$", views.InboxView.as_view(),
        name="inbox"),
    url(r"^create/$", views.MessageCreateView.as_view(),
        name="message_create"),
    url(r"^create/(?P<user_id>\d+)/$", views.MessageCreateView.as_view(),
        name="message_user_create"),
    url(r"^thread/(?P<pk>\d+)/$", views.ThreadView.as_view(),
        name="thread_detail"),
    url(r"^thread/(?P<pk>\d+)/delete/$", views.ThreadDeleteView.as_view(),
        name="thread_delete"),
]

tanbamaapp/tanbama/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

api_urls = [
    url(r'^', include('api.urls')),    
    
]
urlpatterns = [
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    url('', include('django.contrib.auth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^',include('sites.urls')),
    url(r'^site/',include(api_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls)),
    url(r'^accounts/', include('users.urls')),
    url(r'^select2/', include('django_select2.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tanbamaapp/pinax/messages/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from .signals import message_sent
from .utils import cached_attribute
from django_jalali.db import models as jmodels

@python_2_unicode_compatible
class Thread(models.Model):

    subject = models.CharField(max_length=150)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through="UserThread")

    @classmethod
    def inbox(cls, user):
        return cls.objects.filter(userthread__user=user, userthread__deleted=False)

    @classmethod
    def deleted(cls, user):
        return cls.objects.filter(userthread__user=user, userthread__deleted=True)

    @classmethod
    def unread(cls, user):
        return cls.objects.filter(
            userthread__user=user,
            userthread__deleted=False,
            userthread__unread=True
        )

    def __str__(self):
        return "{}: {}".format(
            self.subject,
            ", ".join([str(user) for user in self.users.all()])
        )

    def get_absolute_url(self):
        return reverse("pinax_messages:thread_detail", args=[self.pk])

    @property
    @cached_attribute
    def first_message(self):
        return self.messages.all()[0]

    @property
    @cached_attribute
    def latest_message(self):
        return self.messages.order_by("-sent_at")[0]

    @classmethod
    def ordered(cls, objs):
        """
        Returns the iterable ordered the correct way, this is a class method
        because we don"t know what the type of the iterable will be.
        """
        objs = list(objs)
        objs.sort(key=lambda o: o.latest_message.sent_at, reverse=True)
        return objs


class UserThread(models.Model):

    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    unread = models.BooleanField()
    deleted = models.BooleanField()


class Message(models.Model):

    thread = models.ForeignKey(Thread, related_name="messages", on_delete=models.CASCADE)

    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="sent_messages", on_delete=models.CASCADE)
    sent_at = jmodels.jDateTimeField(_("تاریخ ارسال"), auto_now_add=True)

    content = models.TextField()

    @classmethod
    def new_reply(cls, thread, user, content):
        """
        Create a new reply for an existing Thread.

        Mark thread as unread for all other participants, and
        mark thread as read by replier.
        """
        msg = cls.objects.create(thread=thread, sender=user, content=content)
        thread.userthread_set.exclude(user=user).update(deleted=False, unread=True)
        thread.userthread_set.filter(user=user).update(deleted=False, unread=False)
        message_sent.send(sender=cls, message=msg, thread=thread, reply=True)
        return msg

    @classmethod
    def new_message(cls, from_user, to_users, subject, content):
        """
        Create a new Message and Thread.

        Mark thread as unread for all recipients, and
        mark thread as read and deleted from inbox by creator.
        """
        thread = Thread.objects.create(subject=subject)
        for user in to_users:
            thread.userthread_set.create(user=user, deleted=False, unread=True)
        thread.userthread_set.create(user=from_user, deleted=True, unread=False)
        msg = cls.objects.create(thread=thread, sender=from_user, content=content)
        message_sent.send(sender=cls, message=msg, thread=thread, reply=False)
        return msg

    class Meta:
        ordering = ("sent_at",)

    def get_absolute_url(self):
        return self.thread.get_absolute_url()

tanbamaapp/pinax/messages/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from .hooks import hookset
from .models import Message


class UserModelChoiceField(forms.ModelChoiceField):

    def label_from_instance(self, obj):
        return hookset.display_name(obj)


class UserModelMultipleChoiceField(forms.ModelMultipleChoiceField):

    def label_from_instance(self, obj):
        return hookset.display_name(obj)


class NewMessageForm(forms.ModelForm):

    subject = forms.CharField(label=_('موضوع'))
    to_user = UserModelChoiceField(label=_('به '), queryset=get_user_model().objects.none())
    content = forms.CharField(label=_('محتوا'), widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(NewMessageForm, self).__init__(*args, **kwargs)
        self.fields["to_user"].queryset = hookset.get_user_choices(self.user)
        if self.initial.get("to_user") is not None:
            qs = self.fields["to_user"].queryset.filter(pk=self.initial["to_user"])
            self.fields["to_user"].queryset = qs

    def save(self, commit=True):
        data = self.cleaned_data
        return Message.new_message(
            self.user, [data["to_user"]], data["subject"], data["content"]
        )

    class Meta:
        model = Message
        fields = ["to_user", "subject", "content"]


class NewMessageFormMultiple(forms.ModelForm):
    subject = forms.CharField()
    to_user = UserModelMultipleChoiceField(get_user_model().objects.none())
    content = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(NewMessageFormMultiple, self).__init__(*args, **kwargs)
        self.fields["to_user"].queryset = hookset.get_user_choices(self.user)
        if self.initial.get("to_user") is not None:
            qs = self.fields["to_user"].queryset.filter(pk__in=self.initial["to_user"])
            self.fields["to_user"].queryset = qs

    def save(self, commit=True):
        data = self.cleaned_data
        return Message.new_message(
            self.user, data["to_user"], data["subject"], data["content"]
        )

    class Meta:
        model = Message
        fields = ["to_user", "subject", "content"]


class MessageReplyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.thread = kwargs.pop("thread")
        self.user = kwargs.pop("user")
        super(MessageReplyForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        return Message.new_reply(
            self.thread, self.user, self.cleaned_data["content"]
        )

    class Meta:
        model = Message
        fields = ["content"]

tanbamaapp/pinax/messages/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DeleteView,
    TemplateView,
    UpdateView
)

from .forms import MessageReplyForm, NewMessageForm, NewMessageFormMultiple
from .models import Thread

try:
    from account.decorators import login_required
except:  # noqa
    from django.contrib.auth.decorators import login_required


class InboxView(TemplateView):
    """
    View inbox thread list.
    """
    template_name = "pinax/messages/inbox.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(InboxView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(InboxView, self).get_context_data(**kwargs)
        if self.kwargs.get("deleted", None):
            threads = Thread.ordered(Thread.deleted(self.request.user))
            folder = "deleted"
        else:
            threads = Thread.ordered(Thread.inbox(self.request.user))
            folder = "inbox"

        context.update({
            "folder": folder,
            "threads": threads,
            "threads_unread": Thread.ordered(Thread.unread(self.request.user))
        })
        return context


class ThreadView(UpdateView):
    """
    View a single Thread or POST a reply.
    """
    model = Thread
    form_class = MessageReplyForm
    context_object_name = "thread"
    template_name = "pinax/messages/thread_detail.html"
    success_url = reverse_lazy("pinax_messages:inbox")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        qs = super(ThreadView, self).get_queryset()
        qs = qs.filter(userthread__user=self.request.user).distinct()
        return qs

    def get_form_kwargs(self):
        kwargs = super(ThreadView, self).get_form_kwargs()
        kwargs.update({
            "user": self.request.user,
            "thread": self.object
        })
        return kwargs

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        self.object.userthread_set.filter(user=request.user).update(unread=False)
        return response


class MessageCreateView(CreateView):
    """
    Create a new thread message.
    """
    template_name = "pinax/messages/message_create.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MessageCreateView, self).dispatch(*args, **kwargs)

    def get_form_class(self):
        if self.form_class is None:
            if self.kwargs.get("multiple", False):
                return NewMessageFormMultiple
        return NewMessageForm

    def get_initial(self):
        user_id = self.kwargs.get("user_id", None)
        if user_id is not None:
            user_id = [int(user_id)]
        elif "to_user" in self.request.GET and self.request.GET["to_user"].isdigit():
            user_id = map(int, self.request.GET.getlist("to_user"))
        if not self.kwargs.get("multiple", False) and user_id:
            user_id = user_id[0]
        return {"to_user": user_id}

    def get_form_kwargs(self):
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        kwargs.update({
            "user": self.request.user,
        })
        return kwargs


class ThreadDeleteView(DeleteView):
    """
    Delete a thread.
    """
    model = Thread
    success_url = reverse_lazy("pinax_messages:inbox")
    template_name = "pinax/messages/thread_confirm_delete.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadDeleteView, self).dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.userthread_set.filter(user=request.user).update(deleted=True)
        return HttpResponseRedirect(success_url)

tanbamaapp/templates/pinax/messages/base.html
{% extends "site_base.html" %}

{% block body_class %}pinax-messages{% endblock %}

tanbamaapp/templates/pinax/messages/inbox.html
{% extends "../../sites/base_site.html" %}
{% load i18n %}
{% load pinax_messages_tags %}
{% block title %} صندوق ورودی {% endblock title %}

​{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block location %}
صندوق ورودی
{% endblock location %}

{% block content %}
<div class="container-fluid">
    <div class="list-group">
    <section class="actions-header">
        <div class="row">
            <h1>صندوق ورودی</h1>
            <div class="col-sm-12">
                <a class="btn btn-success pull-right" href="{% url "pinax_messages:message_create" %}">پیام جدید</a>
            </div>
        </div>
    </section>
​
    <section class="mailbox">
        {% for thread in threads %}
            <div class="thread {% if thread|unread:user %}unread{% endif %}">
                <a class="list-group-item" href="{{thread.get_absolute_url}}" >
                    <div class="row">
                        <span class="col-sm-2 users">{{ thread.users.all|join:", " }}</span>
                        <div class="col-sm-10">
                            <p class="subject">{{ thread.subject }}</p>
                            <p class="content text-muted">{{ thread.latest_message.content }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% empty %}
            <div>You have no messages.</div>
        {% endfor %}
    </section>
</div>
</div>
{% endblock content %}            
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %}      

tanbamaapp/templates/pinax/messages/message_create.html
{% extends "../../sites/base_site.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load pinax_messages_tags %}
{% block title %} پیام جدید {% endblock title %}

​{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block location %}
پیام جدید
{% endblock location %}

{% block content %}
<div class="container-fluid">

    <h2>پیام جدید</h2>

    <section>
        <form class="comment-form" action="{% url "pinax_messages:message_create" %}" method="post">
            {% csrf_token %}
            <div class="col-sm-5">
            {% bootstrap_form form %}
            
                    <button class="btn btn-primary pull-right">ارسال</button>
                </form>
                <a class="btn btn-default" href="{% url "pinax_messages:inbox" %}">لغو</a>
            </div>
    </section>
{% endblock %}

tanbamaapp/templates/pinax/messages/thread_detail.html
{% extends "../../sites/base_site.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% load pinax_messages_tags %}
{% block title %} مکالمه {% endblock title %}

​{% block stylesheets %}
{{ block.super }}
<style type="text/css">
    body {
		font-family: 'Varela Round', sans-serif;
	}
	.modal-confirm {		
		color: #636363;
		width: 400px;
	}
	.modal-confirm .modal-content {
		padding: 20px;
		border-radius: 5px;
		border: none;
        text-align: center;
		font-size: 14px;
	}
	.modal-confirm .modal-header {
		border-bottom: none;   
        position: relative;
	}
	.modal-confirm h4 {
		text-align: center;
		font-size: 26px;
		margin: 30px 0 -10px;
	}
	.modal-confirm .close {
        position: absolute;
		top: -5px;
		right: -2px;
	}
	.modal-confirm .modal-body {
		color: #999;
	}
	.modal-confirm .modal-footer {
		border: none;
		text-align: center;		
		border-radius: 5px;
		font-size: 13px;
		padding: 10px 15px 25px;
	}
	.modal-confirm .modal-footer a {
		color: #999;
	}		
	.modal-confirm .icon-box {
		width: 80px;
		height: 80px;
		margin: 0 auto;
		border-radius: 50%;
		z-index: 9;
		text-align: center;
		border: 3px solid #f15e5e;
	}
	.modal-confirm .icon-box i {
		color: #f15e5e;
		font-size: 46px;
		display: inline-block;
		margin-top: 13px;
	}
    .modal-confirm .btn {
        color: #fff;
        border-radius: 4px;
		background: #60c7c1;
		text-decoration: none;
		transition: all 0.4s;
        line-height: normal;
		min-width: 120px;
        border: none;
		min-height: 40px;
		border-radius: 3px;
		margin: 0 5px;
		outline: none !important;
    }
	.modal-confirm .btn-info {
        background: #c1c1c1;
    }
    .modal-confirm .btn-info:hover, .modal-confirm .btn-info:focus {
        background: #a8a8a8;
    }
    .modal-confirm .btn-danger {
        background: #f15e5e;
    }
    .modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
        background: #ee3535;
    }
	.trigger-btn {
		display: inline-block;
		margin: 100px auto;
	}
</style>
{% endblock stylesheets %}

{% block location %}
مکالمه  
{% endblock location %}

{% block content %}
<div class="container-fluid">
    
    <div class="pinax-messages-thread-detail-container">
        <h3 href="#myModal" class="with-actions">{{ thread.subject }}
        <a href="#myModal" class="trigger-btn" data-toggle="modal"><i class="far fa-trash-alt"></i> حذف مکالمه</a>
        </h3>
        <section class="thread-messages">
            {% for message in thread.messages.all %}
                <div class="thread-message">
                    <div class="message-byline">
                        <div class="message-from">{{ message.sender.username }}</div>
                        <div class="message-sent">{{ message.sent_at }}</div>
                    </div>
                    <div class="message-content">{{ message.content|urlize|linebreaks }}</div>
                </div>
            {% endfor %}
        </section>

        <form class="comment-form" action="{% url "pinax_messages:thread_detail" thread.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form-actions">
                <a href="{% url "pinax_messages:inbox" %}" class="cancel">لغو</a>
                <button>ارسال</button>
            </div>
        </form>
    </div>

    <div id="myModal" class="modal fade">
            <div class="modal-dialog modal-confirm">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="icon-box">
                                <i class="far fa-trash-alt"></i>
                        </div>				
                        <h4 class="modal-title">اطمینان دارید؟</h4>	
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>از پاک کردن این مکالمه اطمینان دارید؟</p>
                        <p>{% url "pinax_messages:thread_delete" thread.pk as post_url %}</p>
                    </div>
                    <div class="modal-footer">
                        <form action="{{ post_url }}" method="POST" class="form form-horizontal">
                            {% csrf_token %}
                            <div class="form-actions">
                                <button type="button" class="btn btn-info" data-dismiss="modal">لغو</button>
                                <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>     
</div>
{% endblock content %}            
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %}      