tanbamaapp/api/urls.py
from django.conf.urls import url, include
from .views import UserRegistrationAPIView, WeightListCreateAPIView, WeightDetailAPIView, DrugListCreateAPIView, RxListCreateAPIView, RxDetailAPIView, DrugDetailAPIView
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

api_user = [
    url(r'^$', UserRegistrationAPIView.as_view(), name="list"),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-token-refresh/', refresh_jwt_token),
    
]

api_body = [
    url(r'^weight/$', WeightListCreateAPIView.as_view(), name="list"),
    url(r'^weight/(?P<pk>[0-9]+)/$', WeightDetailAPIView.as_view(), name="detail"),
    url(r'^drug/$', DrugListCreateAPIView.as_view(), name="list"),
    url(r'^drug/(?P<pk>[0-9]+)/$', DrugDetailAPIView.as_view(), name="detail"),
    url(r'^rx/$', RxListCreateAPIView.as_view(), name="list"),
    url(r'^rx/(?P<pk>[0-9]+)/$', RxDetailAPIView.as_view(), name="detail"),
    
]

    


urlpatterns = [
    url(r'^body/', include(api_body)),
    url(r'^user/', include(api_user)),
]

tanbamaapp/pinax/messages/urls.py
from django.conf.urls import url

from . import views

app_name = "pinax_messages"

urlpatterns = [
    url(r"^inbox/$", views.InboxView.as_view(),
        name="inbox"),
    url(r"^create/$", views.MessageCreateView.as_view(),
        name="message_create"),
    url(r"^create/(?P<user_id>\d+)/$", views.MessageCreateView.as_view(),
        name="message_user_create"),
    url(r"^thread/(?P<pk>\d+)/$", views.ThreadView.as_view(),
        name="thread_detail"),
    url(r"^thread/(?P<pk>\d+)/delete/$", views.ThreadDeleteView.as_view(),
        name="thread_delete"),
]

tanbamaapp/sites/urls.py
from django.conf.urls import url
from sites import views
from body.models import Weight, Drug, Food




urlpatterns = [
    # Matches any html file - to be used for tanbama
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    # url(r'^.*\.html', views.SitehtmlView.as_view(), name='tanbama'),

    # The home page
    url(r'^$', views.index, name='index'),
    url(r'^weight/list$', views.WeightList.as_view(), name='weights_list'),
    # url(r'^food/list$', views.FoodList.as_view(), name='food_list'),
    url(r'^users/list$', views.UserList.as_view(), name='users_list'),
    url(r'^home/$', views.HomeView.as_view(), name='dashboard'),
    url(r'^profile/(?P<pk>[\w]+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/edit/(?P<pk>[\w]+)/$', views.ProfileUpdate.as_view(), name='profile_edit'),
    url(r'^rx/$', views.RxView.as_view(), name='rx'),
    url(r'^goal/$', views.GoalView.as_view(), name='goal'),
    url(r'^goal/create$', views.GoalCreate.as_view(), name='gbw_create'),
    url(r'^program/create$', views.FoodProgramCreate.as_view(), name='program_create'),
    url(r'^food/$', views.FoodList.as_view(), name='food_list'),
    url(r'^food/create$', views.FoodCreate.as_view(), name='food_create'),
    url(r'^food/(?P<pk>[\w]+)/$', views.FoodShow.as_view(), name='food_show'),
    url(r'^food/update/(?P<pk>[\w]+)/$', views.FoodUpdate.as_view(
        model=Food,
    ), name='food_update'),
    url(r'^food/delete/(?P<pk>[\w]+)/$', views.FoodDelete.as_view(
        model=Food,
    ), name='food_delete'),
    url(r'^drug/$', views.DrugList.as_view(), name='drug'),
    url(r'^drug/create$', views.CreateDrug.as_view(), name='drug_create'),
    url(r'^weight/create$', views.WeightCreate.as_view(), name='weight_create'),
    url(r'^weight/(?P<pk>[\w]+)/$', views.WeightShow.as_view(), name='weight_show'),
    url(r'^weight/update/(?P<pk>[\w]+)/$', views.WeightUpdate.as_view(
        model=Weight,
    ), name='weight_update'),
    url(r'^weight/delete/(?P<pk>[\w]+)/$', views.WeightDelete.as_view(
        model=Weight,
    ), name='weight_delete'),
]

tanbamaapp/tanbama/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

api_urls = [
    url(r'^', include('api.urls')),    
    
]
urlpatterns = [
    url(r"^messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    url('', include('django.contrib.auth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^',include('sites.urls')),
    url(r'^site/',include(api_urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urls)),
    url(r'^accounts/', include('users.urls')),
    url(r'^select2/', include('django_select2.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tanbamaapp/sites/models.py
from django.db import models

# Create your models here.

tanbamaapp/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.contenttypes.models import ContentType
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from .conf import settings
from .managers import UserInheritanceManager, UserManager
from django_jalali.db import models as jmodels

class AbstractUser(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('M', _("مرد")),
        ('F', _("زن"))
    )
    
    USERS_AUTO_ACTIVATE = not settings.USERS_VERIFY_EMAIL

    first_name = models.CharField(_('نام'), max_length=255 , null=True)
    last_name = models.CharField(_('نام خانوادگی'), max_length=255 , null=True)
    birthday = jmodels.jDateTimeField(_('تاریخ تولد'), null=True)
    gender = models.CharField(_('جنسیت'),max_length=1, null=True, choices=GENDER_CHOICES, default='M')

    email = models.EmailField(
        _('آدرس ایمیل'), max_length=255, unique=True, db_index=True)
    is_staff = models.BooleanField(
        _('وضعیت کاربر'), default=False,
        help_text=_('تعیین اینکه آیا کاربر میتواند به بخش مدیریت وارد شود یا خیر.'))

    is_active = models.BooleanField(
        _('فعال'), default=USERS_AUTO_ACTIVATE,
        help_text=_('مشخص میکند که کاربر فعال است یا خیر '
                    'به جای حذف حساب کاربری این قسمت را غیرفعال کنید.'))
    date_joined = jmodels.jDateTimeField(_('زمان عضویت'), auto_now_add=True, blank=True)
    user_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True, editable=False)

    objects = UserInheritanceManager()
    base_objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        abstract = True
    

    def get_full_name(self):
        
        return "{} {}".format( self.first_name, self.last_name )
    
    def get_short_name(self):
        """ Return the first_name."""
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """ Send an email to this User."""
        send_mail(subject, message, from_email, [self.email])

    def activate(self):
        self.is_active = True
        self.save()

    def save(self, *args, **kwargs):
        if not self.user_type_id:
            self.user_type = ContentType.objects.get_for_model(self, for_concrete_model=False)
        super(AbstractUser, self).save(*args, **kwargs)


class User(AbstractUser):

    """
    Concrete class of AbstractUser.
    Use this if you don't need to extend User.
    """
    is_doctor = models.BooleanField('docktor status', default=False)
    is_patient = models.BooleanField('patient status', default=True)

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'


class Patient(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    ssn = models.CharField(max_length=9, unique=True)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=5)

    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name


class DoctorSpeciality(models.Model):
    specialty = models.CharField(max_length=30, primary_key=True)

    def __unicode__(self):
        return self.specialty

    class Meta:
        verbose_name_plural = 'Doctors specialties'

class Doctor(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    specialty = models.ForeignKey(DoctorSpeciality)


    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name

tanbamaapp/sites/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from users.models import User
from django.conf import settings
from body.models import Weight, Gbw, Drug, Food, FoodProgram
from django_select2.forms import Select2MultipleWidget

class UserCreationForm(forms.ModelForm):
    email = forms.EmailField(label='ایمیل', max_length=255)
    password1 = forms.CharField(label='گذرواژه', widget=forms.PasswordInput)
    password2 = forms.CharField(label='گذرواژه مجدد', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2


class WeightCreateForm(forms.ModelForm):
    """                                                                                                                            
    Use to create Weight                                                                                                           
    """
    class Meta(object):
        model = Weight
        fields = ('weight', 'height', 'text')
        # user will be set in views.ResumeNew                                                                                      
        # other fields will be set as model default                                                                                

class DrugCreateForm(forms.ModelForm):
    """                                                                                                                            
    Use to create Weight                                                                                                           
    """
    salt = forms.CharField(label="ملح" , max_length=255, required=False)
    dosage_form = forms.CharField(label= "شکل دارویی", max_length=255, required=False)
    strengh = forms.CharField(label="مقدار دارو", max_length=255, required=False)
    route_of_admin = forms.CharField(label="راه مصرف", max_length=255, required=False)
    atcـcode = forms.CharField(label="دسته دارو", max_length=255, required=False)
    ingredient = forms.CharField(label="ترکیبات", max_length=255, required=False)
    remarks = forms.CharField(label="توضیحات", max_length=255, required=False)
    class Meta(object):
        model = Drug
        fields = ('name', 'salt', 'dosage_form', 'strengh', 'route_of_admin', 'atcـcode', 'ingredient', 'remarks')


class GbwCreateForm(forms.ModelForm):
    """                                                                                                                            
    Use to create Weight                                                                                                           
    """
    class Meta(object):
        model = Gbw
        fields = ('gbw',)

class FoodCreateForm(forms.ModelForm):
    """                                                                                                                            
    Use to create Food                                                                                                           
    """
   
    class Meta(object):
        model = Food
        fields = ('name','amount', 'unit', 'calories', 'details')

class FoodProgramForm(forms.ModelForm):
    """
    this is for food program
    """
    breakfest = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    bm = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    lounch = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    lm = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    dinner = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    dm = forms.ModelMultipleChoiceField(queryset=Food.objects.values_list('name', flat=True).all(), widget=Select2MultipleWidget)
    class Meta(object):
        model = FoodProgram
        fields = ('breakfest','bm', 'lounch', 'lm', 'dinner','dm')


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_staff')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]



class ProfileUpdateForm(forms.ModelForm):
    birthday = forms.DateField(label='تاریخ تولد',input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'birthday', 'gender','email')

tanbamaapp/templates/sites/base_site.html
{% load avatar_tags %}
{% load static %}
{% load i18n %}
{% load pinax_messages_tags %}




<!--
 * CoreUI - Open Source Bootstrap Admin Template
 * @version v1.0.0-alpha.2
 * @link http://coreui.io
 * Copyright (c) 2016 creativeLabs Łukasz Holeczek
 * @license MIT
 -->
<!DOCTYPE html>
<html lang="IR-fa" dir="rtl">

<head>
    {% block head %}
        {% block meta %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta name="description" content="تنباما">
            <meta name="keyword" content="تنباما">
            <!-- <link rel="shortcut icon" href="assets/ico/favicon.png"> -->
            
        {% endblock meta %}
            <title>
                {% block title %}
                {% endblock title %}
            </title>
            <!-- Icons -->
            <link href="{% static "css/font-awesome.min.css" %}"  rel="stylesheet">
            <link href="{% static "css/simple-line-icons.css" %}"  rel="stylesheet">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
            {{ form.media.css }}
        {% block stylesheets %}
            <!-- Main styles for this application -->
            <link href="{% static "dest/style.css" %}"  rel="stylesheet">
        {% endblock stylesheets %}  
    {% endblock head %}
</head>
<!-- BODY options, add following classes to body to change options
		1. 'compact-nav'     	  - Switch sidebar to minified version (width 50px)
		2. 'sidebar-nav'		  - Navigation on the left
			2.1. 'sidebar-off-canvas'	- Off-Canvas
				2.1.1 'sidebar-off-canvas-push'	- Off-Canvas which move content
				2.1.2 'sidebar-off-canvas-with-shadow'	- Add shadow to body elements
		3. 'fixed-nav'			  - Fixed navigation
		4. 'navbar-fixed'		  - Fixed navbar
	-->
{% block body %}
<body class="navbar-fixed sidebar-nav fixed-nav">
    {% block top_navigation %}
    {% endblock top_navigation %}
    <header class="navbar">
        <div class="container-fluid">
            <button class="navbar-toggler mobile-toggler hidden-lg-up" type="button">&#9776;</button>
            <a class="navbar-brand" href="#"></a>
            <ul class="nav navbar-nav hidden-md-down">
                <li class="nav-item">
                    <a class="nav-link navbar-toggler layout-toggler" href="#">&#9776;</a>
                </li>

                <!--<li class="nav-item p-x-1">
                    <a class="nav-link" href="#">داشبورد</a>
                </li>
                <li class="nav-item p-x-1">
                    <a class="nav-link" href="#">Users</a>
                </li>
                <li class="nav-item p-x-1">
                    <a class="nav-link" href="#">Settings</a>
                </li>-->
            </ul>
            <ul class="nav navbar-nav pull-left hidden-md-down">
                <li class="nav-item">
                    <a class="nav-link aside-toggle" href="#"><i class="icon-bell"></i><span class="tag tag-pill tag-danger">

                        {% with user|unread_thread_count as user_unread %}
                            {{ user_unread }}
                        {% endwith %}

                    </span></a>
                </li>                
                <li class="nav-item dropdown">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            {% avatar user 50 class="img-circle img-responsive" id="user_avatar" %}
                            <span class="hidden-md-down">{{user.get_full_name}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="dropdown-header text-xs-center">
                                <strong>تنظیمات</strong>
                            </div>
                            <a class="dropdown-item" href="/profile/{{user.id}}/"><i class="fa fa-user"></i> پروفایل</a>
                            <a class="dropdown-item" href="/profile/edit/{{user.id}}/"><i class="fa fa-wrench"></i> تنظیمات</a>
                            <!--<a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="tag tag-default">42</span></a>-->
                            <div class="divider"></div>
                            <a class="dropdown-item" href="/accounts/logout/"><i class="fa fa-lock"></i> خروج</a>
                        </div>
                    </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-toggler aside-toggle" href="#">&#9776;</a>
                </li>

            </ul>
        </div>
    </header>
    {% block sidebar %}
        {% include "sites/sidebar.html" %}
    {% endblock sidebar %}
    </div>
    <!-- Main content -->
    <main class="main">

        <!-- Breadcrumb -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">خانه</li>
            <li class="breadcrumb-item active">
                {% block location %}
                {% endblock location %}
            </li>

            <!-- Breadcrumb Menu-->
            <li class="breadcrumb-menu">
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <a class="btn btn-secondary" href="/"><i class="icon-graph"></i> &nbsp;داشبورد</a>
                    <a class="btn btn-secondary" href="/profile/edit/{{user.id}}/"><i class="icon-settings"></i> &nbsp;تنظیمات</a>
                </div>
            </li>
        </ol>
    {% block content %} 
        <!--/.container-fluid-->
    </main>
    {% endblock content %}
    

    <aside class="aside-menu">

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="timeline" role="tabpanel">
                <div class="tab-pane p-a-1" id="messages" role="tabpanel">
                        <div class="message">
                        {% for thread in unread_threads %}
                        <div class="thread {% if thread|unread:user %}unread{% endif %}">
                            <a href="{{thread.get_absolute_url}}">
                                
                                <div class="participants">
        
                                        
                                        {% avatar thread.latest_message.sender  25 class="img-circle img-responsive" id="user_avatar" %}
                                        </div>
                                    <div class="latest-message">
                                        <p class="subject">{{ thread.subject }}</p>
                                    </div>
                                    <hr>
                                </div>
                                
                            </a>
                        </div>
                            {% empty %}
                                <div class="no-messages">شما پیامی ندارید.</div>
                        </div>
                        <hr>
                        {% endfor %}
                        
                </div>
        </div>

        </div>        
    </aside>
    {% block footer %}
    <footer class="footer">
        <span class="text-left">
            <a href="http://www.tanbama.ir">تنباما</a>
        </span>
        <span class="pull-right">     
                با افتخار <i class="fa fa-heart heart"></i> GPL3 . 
        </span>
    </footer>
    {% endblock footer %}

    {% block javascripts %}
    <!-- Bootstrap and necessary qplugins -->
    <script src="{% static "js/libs/jquery.min.js" %}"  ></script>
    <script src="{% static "js/libs/tether.min.js" %}"  ></script>
    <script src="{% static "js/libs/bootstrap.min.js" %}"  ></script>
    <script src="{% static "js/libs/pace.min.js" %}"  ></script>

    <!-- Plugins and scripts required by all views -->
    <script src="{% static "js/libs/Chart.min.js" %}"  ></script>

    <!-- CoreUI main scripts -->

    <script src="{% static "js/app.js" %}"  ></script>

    <!-- Plugins and scripts required by this views -->
    <!-- Custom scripts required by this view -->
    <script src="{% static "js/views/main.js" %}"  ></script>

    <!-- Grunt watch plugin -->
    <script src="//localhost:8009/livereload.js"></script>
    {{ form.media.js }}
    {% endblock javascripts %}

{% endblock body %}
</body>
</html>

tanbamaapp/templates/sites/chart.html
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<div id="container" style="height: 400px">

<script>
    var categories = [
    {% for entry in dataset %}'{{ entry.date_created|date:'Y-m-d' }}'{% if not forloop.last %}, {% endif %}{% endfor %}
          ]

  Highcharts.chart('container', {
      chart: {
          type: 'line'
      },
      dateRangeGrouping: true,
      
      title: {
          text: 'آخرین تغییرات وزن شما'
      },
      xAxis: {
          categories: categories
                   
      },
      yAxis: {
            title: {
            text: 'کیلوگرم (kg)'
            }
        },
      plotOptions: {
            line: {
            dataLabels: {
                enabled: true     
            },
            // enableMouseTracking: false
            }
        },
      series: [{
          name: 'وزن',
          data: [
            {% for entry in dataset %}{{ entry.weight }}{% if not forloop.last %}, {% endif %}{% endfor %}
          ],
          color: 'green'
      }, 
          ]
  });
</script>

tanbamaapp/templates/sites/dashboard.html
{% extends "sites/base_site.html" %}

{% block title %} داشبورد {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="https://rawgit.com/notryanb/highcharts_date_range_grouping/config-date-formats/dist/highcharts_date_range_grouping.css"> 
  {% endblock stylesheets %}


{% block location %}
داشبورد
{% endblock location %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-lg-6 offset-sm-3">
            <div class="animated fadeIn">
            
                {% if request.user.is_patient %}
                <div class="card">
                        <div class="card-header">
                            تغییرات وزن
                        </div>
                        <div class="card-block">
                            <div class="chart-wrapper">
                                    {% include "sites/chart.html" %}
                            </div>
                            
                        </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    <!--/.container-fluid-->
{% endblock content %}            
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %}

tanbamaapp/templates/sites/profile.html
{% extends "sites/base_site.html" %}
{% load pinax_messages_tags %}
{% load avatar_tags %}
{% load static %}
{% block title %} پروفایل {% endblock title %}
{% load static %}
{% block stylesheets %}
  {{ block.super }}
  <link href="{% static "css/profile.css" %}"  rel="stylesheet">
{% endblock stylesheets %}

{% block location %}
 پروفایل
{% endblock location %}


{% block content %}

<div class="row">
    <div class="a">
        {% if object == request.user and request.user.is_authenticated %}
            <h1>{{ user.first_name }} اینجا صفحه پروفایل شماست!</h1>
        {% endif %}
      
        <div class="profile-header-container">

        <div class="card" style="width:400px">
                <div class="card-img-top" style="width:100%">
                        {% avatar user 128 class="img-circle img-responsive" id="user_avatar"%} </br>
                        {% if object == request.user and request.user.is_authenticated %}
                            <a href="{% url 'avatar_change' %}">نمایه خود را تغییر دهید</a>
                        {% endif %}
                        <!-- badge -->
                    </div>
                <div class="card-body">
                    <h4 class="card-title">{{ user.first_name }} {{ user.last_name }}</h4>
                    <p class="card-text"> جنسیت {{ user.get_gender_display }} </br>
                        تاریخ تولد {{ user.birthday | date:" d-m-Y" }}</p>
                    {% if object == request.user and request.user.is_authenticated %}
                    <a href="/profile/edit/{{user.id}}/" class="btn btn-primary">ویرایش پروفایل</a>
                    {% endif %}
                    <a href="{% url "pinax_messages:message_user_create" user.id %}" class="btn btn-default"> پیام به کاربر</a>
        </div>
    </div>
</div>

{% endblock content %}            
{% block javascripts %}
{{ block.super }}
{% endblock javascripts %} 